#!/usr/bin/env python3
"""
gen_c_weights.py
================
Converts svm_weights.hex and svm_biases.hex (from train.py outputs)
into C array declarations ready to paste into nir_baremetal.c.

Usage:
    python3 gen_c_weights.py \
        --weights outputs/svm_weights.hex \
        --biases  outputs/svm_biases.hex \
        --out     nir_weights.h
"""

import argparse
import pathlib

N_CLASSES  = 5
N_CHANNELS = 224


def load_hex_signed16(path):
    vals = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            v = int(line, 16) & 0xFFFF
            vals.append(v - 65536 if v > 32767 else v)
    return vals


def load_hex_signed32(path):
    vals = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            v = int(line, 16) & 0xFFFFFFFF
            vals.append(v - (1 << 32) if v > 0x7FFFFFFF else v)
    return vals


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--weights", default="outputs/svm_weights.hex")
    p.add_argument("--biases",  default="outputs/svm_biases.hex")
    p.add_argument("--out",     default="nir_weights.h")
    args = p.parse_args()

    weights = load_hex_signed16(args.weights)
    biases  = load_hex_signed32(args.biases)

    assert len(weights) == N_CLASSES * N_CHANNELS, \
        f"Expected {N_CLASSES*N_CHANNELS} weights, got {len(weights)}"
    assert len(biases) == N_CLASSES, \
        f"Expected {N_CLASSES} biases, got {len(biases)}"

    CLASS_NAMES = ["PE", "PP", "PET", "PS", "PVC"]

    lines = []
    lines.append("/* Auto-generated by gen_c_weights.py */")
    lines.append("/* Paste into nir_baremetal.c replacing the SVM_W and SVM_B placeholders */")
    lines.append("")
    lines.append(f"static const s16 SVM_W[{N_CLASSES}][{N_CHANNELS}] = {{")

    for c in range(N_CLASSES):
        row = weights[c * N_CHANNELS : (c + 1) * N_CHANNELS]
        vals = ", ".join(str(v) for v in row)
        lines.append(f"    /* Class {c+1} {CLASS_NAMES[c]} */")
        # wrap at 16 values per line
        chunks = [row[i:i+16] for i in range(0, len(row), 16)]
        formatted = []
        for chunk in chunks:
            formatted.append("    " + ", ".join(str(v) for v in chunk) + ",")
        lines.extend(formatted)
        if c < N_CLASSES - 1:
            lines.append("")

    lines.append("};")
    lines.append("")
    lines.append(f"static const s32 SVM_B[{N_CLASSES}] = {{")
    lines.append("    " + ", ".join(str(v) for v in biases))
    lines.append("};")
    lines.append("")

    out = pathlib.Path(args.out)
    out.write_text("\n".join(lines))
    print(f"Written: {out}")
    print(f"  Weights: {N_CLASSES} x {N_CHANNELS} = {len(weights)} values")
    print(f"  Biases : {len(biases)} values")
    print()
    print("Next: copy contents of nir_weights.h into nir_baremetal.c")
    print("      replacing the SVM_W and SVM_B placeholder arrays")


if __name__ == "__main__":
    main()