#!/usr/bin/env python3
"""
gen_spectra_header.py
=====================
Run this on your Mac in the folder where your CSVs live.

Usage:
    python3 gen_spectra_header.py

Outputs:
    spectra_data.h   — C header with 200 raw spectra + ground-truth labels
                       ready to #include in your Vitis bare-metal project
"""

import numpy as np
import pandas as pd
import os

# ── Config ────────────────────────────────────────────────────────────────────
NUM_SPECTRA   = 200          # how many to export
NUM_CHANNELS  = 224
RANDOM_SEED   = 42

# File names — edit if yours differ
TRAIN_CSV     = "train_unique.csv"
LOW_CSV       = "SpectrumData_2021Y-testSetLowNoise.csv"
HIGH_CSV      = "SpectrumData_2021Y-testSetHighNoise.csv"
DARK_CSV      = "SpectrumData_2021Y-darkcurrent.csv"
OUT_HEADER    = "spectra_data.h"

CLASS_NAMES   = {1: "PE", 2: "PP", 3: "PET", 4: "PS", 5: "PVC"}

# ── Load dark current ─────────────────────────────────────────────────────────
print("[1/4] Loading dark current ...")
dark_df  = pd.read_csv(DARK_CSV)
dark_ref = dark_df.select_dtypes(include=[np.number]).mean(axis=0).values.astype(np.float32)
assert dark_ref.shape[0] == NUM_CHANNELS, \
    f"Dark ref has {dark_ref.shape[0]} channels, expected {NUM_CHANNELS}"
print(f"      Dark ref: mean={dark_ref.mean():.1f}  min={dark_ref.min():.0f}  max={dark_ref.max():.0f}")

# ── Load test spectra (prefer low-noise, pad with high-noise if needed) ───────
print("[2/4] Loading test spectra ...")

def load_csv(path):
    df = pd.read_csv(path)
    y  = df["class_id"].values.astype(np.int32)
    # raw ADC columns start after the first 3 metadata cols
    X  = df.iloc[:, 3:3+NUM_CHANNELS].values.astype(np.float32)
    return X, y

X_low,  y_low  = load_csv(LOW_CSV)
X_high, y_high = load_csv(HIGH_CSV)

print(f"      Low-noise  : {X_low.shape[0]} spectra")
print(f"      High-noise : {X_high.shape[0]} spectra")

# Pick balanced sample: equal per class across low-noise, top up from high-noise
rng = np.random.default_rng(RANDOM_SEED)

indices_low  = np.arange(len(y_low))
indices_high = np.arange(len(y_high))
rng.shuffle(indices_low)
rng.shuffle(indices_high)

classes = sorted(CLASS_NAMES.keys())
per_class = NUM_SPECTRA // len(classes)   # 40 per class
extra     = NUM_SPECTRA - per_class * len(classes)

selected_X = []
selected_y = []

for i, cls in enumerate(classes):
    need = per_class + (1 if i < extra else 0)
    pool_idx = indices_low[y_low[indices_low] == cls]
    if len(pool_idx) < need:
        # top up from high-noise
        hi_idx = indices_high[y_high[indices_high] == cls]
        pool_idx = np.concatenate([pool_idx, hi_idx])
    chosen = pool_idx[:need]
    # figure out which dataset each chosen index came from
    for idx in chosen:
        if idx < len(y_low) and y_low[idx] == cls:
            selected_X.append(X_low[idx])
            selected_y.append(y_low[idx])
        else:
            # re-look in high noise
            hi_pool = indices_high[y_high[indices_high] == cls]
            selected_X.append(X_high[hi_pool[0]])
            selected_y.append(y_high[hi_pool[0]])

# Safer: just pick directly
selected_X = []
selected_y = []
for i, cls in enumerate(classes):
    need = per_class + (1 if i < extra else 0)
    mask = (y_low == cls)
    Xi   = X_low[mask]
    yi   = y_low[mask]
    if len(yi) < need:
        mask_h = (y_high == cls)
        Xi = np.vstack([Xi, X_high[mask_h]])
        yi = np.concatenate([yi, y_high[mask_h]])
    perm = rng.permutation(len(yi))[:need]
    selected_X.append(Xi[perm])
    selected_y.append(yi[perm])

X_sel = np.vstack(selected_X)   # (200, 224) raw uint16
y_sel = np.concatenate(selected_y)

# Shuffle the final list so classes are interleaved
perm  = rng.permutation(len(y_sel))
X_sel = X_sel[perm]
y_sel = y_sel[perm]

print(f"      Selected   : {X_sel.shape[0]} spectra  "
      f"(classes: {dict(zip(*np.unique(y_sel, return_counts=True)))})")

# ── Clamp raw values to uint16 ────────────────────────────────────────────────
X_u16 = np.clip(np.round(X_sel), 0, 65535).astype(np.uint16)

# ── Write C header ────────────────────────────────────────────────────────────
print("[3/4] Writing header ...")

lines = []
lines.append("/* spectra_data.h — AUTO-GENERATED by gen_spectra_header.py")
lines.append(" * DO NOT EDIT BY HAND")
lines.append(f" * {NUM_SPECTRA} spectra × {NUM_CHANNELS} channels, raw 16-bit ADC")
lines.append(" * Balanced across PE/PP/PET/PS/PVC from Mendeley 2021Y dataset")
lines.append(" */")
lines.append("")
lines.append("#ifndef SPECTRA_DATA_H")
lines.append("#define SPECTRA_DATA_H")
lines.append("")
lines.append(f"#define NUM_SPECTRA   {NUM_SPECTRA}")
lines.append(f"#define NUM_CHANNELS  {NUM_CHANNELS}")
lines.append("")
lines.append("/* Ground-truth class IDs: 1=PE 2=PP 3=PET 4=PS 5=PVC */")
lines.append(f"static const unsigned char gt_labels[{NUM_SPECTRA}] = {{")
label_row = "    " + ", ".join(str(int(v)) for v in y_sel)
lines.append(label_row)
lines.append("};")
lines.append("")
lines.append('static const char* const class_names[] = {"", "PE", "PP", "PET", "PS", "PVC"};')
lines.append("")
lines.append(f"/* Raw ADC values: uint16, shape [{NUM_SPECTRA}][{NUM_CHANNELS}] */")
lines.append(f"static const unsigned short spectra_raw[{NUM_SPECTRA}][{NUM_CHANNELS}] = {{")

for i in range(NUM_SPECTRA):
    vals = ", ".join(f"{int(v)}" for v in X_u16[i])
    comma = "," if i < NUM_SPECTRA - 1 else ""
    lines.append(f"    /* [{i:03d}] {CLASS_NAMES[int(y_sel[i])]:>3} */ {{{vals}}}{comma}")

lines.append("};")
lines.append("")
lines.append("#endif /* SPECTRA_DATA_H */")

with open(OUT_HEADER, "w") as f:
    f.write("\n".join(lines) + "\n")

# ── Also write dark_current.hex (in case you need to regenerate) ──────────────
print("[4/4] Writing dark_current.hex ...")
dark_u16 = np.clip(np.round(dark_ref), 0, 65535).astype(np.int32)
with open("dark_current.hex", "w") as f:
    for v in dark_u16:
        f.write(f"{int(v):04X}\n")

print()
print("Done!")
print(f"  {OUT_HEADER}       → copy to your Vitis project src/")
print(f"  dark_current.hex  → copy to your Vivado project (for dark_correct.v $readmemh)")
print()

# ── Quick sanity check ────────────────────────────────────────────────────────
print("Sanity check — class distribution in exported set:")
for cls in classes:
    n = int(np.sum(y_sel == cls))
    print(f"  {CLASS_NAMES[cls]:>3} (class {cls}): {n} spectra")