"""
train_svm_rtl.py
================
Reads RTL simulation hex files + labels.txt, trains a LinearSVC,
quantises weights to Q15 (INT16), and writes svm_q15_model.h
ready to drop into your CCS project.

Usage:
    python train_svm_rtl.py
    python train_svm_rtl.py --hex-dir ./hex_files --labels labels.txt --output svm_q15_model.h

Requirements:
    pip install numpy scikit-learn
"""

import argparse
import glob
import os
import sys
import numpy as np
from sklearn.svm import LinearSVC
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score

# ── Constants ──────────────────────────────────────────────────────────────
NUM_FEATURES = 224
Q15_MAX      =  32767
Q15_MIN      = -32768
Q15_SCALE    =  32767.0   # scale float weights into Q15 range

CLASS_NAMES  = ["PE", "PP", "PET", "PS", "PVC"]   # fixed order, 1-indexed on MCU


# ── File parsers ───────────────────────────────────────────────────────────

def parse_hex_file(path):
    """
    Reads one features_NNN.hex file.
    Format: one hex byte per line, e.g. 'FF' (no 0x prefix).
    Returns numpy array of 224 signed int8 values.
    """
    values = []
    with open(path, "r") as fh:
        for raw in fh:
            tok = raw.strip().lower().replace("0x", "")
            if not tok or tok.startswith("#") or tok.startswith("//"):
                continue
            bv = int(tok, 16) & 0xFF
            # Convert unsigned byte to signed int8
            values.append(bv - 256 if bv > 127 else bv)

    if len(values) != NUM_FEATURES:
        raise ValueError(f"{path}: expected {NUM_FEATURES} values, got {len(values)}")
    return np.array(values, dtype=np.int8)


def parse_labels(path):
    """
    Reads labels.txt.
    Format per line: 000  2  PP
    Skips header row if present (first column not a zero-padded number).
    Returns dict: { "000": "PP", "001": "PS", ... }
    """
    labels = {}
    with open(path, "r") as fh:
        for lineno, raw in enumerate(fh, 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 3:
                continue
            # Skip header row — first column should be a digit string
            if not parts[0].isdigit():
                print(f"  [INFO] Skipping header row (line {lineno}): '{line}'")
                continue
            idx_str    = parts[0]   # e.g. "000"
            class_name = parts[2]   # e.g. "PP"
            labels[idx_str] = class_name
    return labels


# ── Q15 quantisation ───────────────────────────────────────────────────────

def quantise_to_q15(weights_float):
    """
    Scale a float array to Q15 INT16.
    Uses the per-row max to maximise dynamic range per class.
    Returns INT16 array, same shape.
    """
    result = np.zeros_like(weights_float, dtype=np.int16)
    for i in range(weights_float.shape[0]):
        row     = weights_float[i]
        abs_max = np.max(np.abs(row))
        if abs_max == 0:
            result[i] = 0
            continue
        scale      = Q15_MAX / abs_max
        scaled     = np.round(row * scale).astype(np.int32)
        result[i]  = np.clip(scaled, Q15_MIN, Q15_MAX).astype(np.int16)
    return result


def quantise_bias_to_q15(biases_float, weight_scales):
    """
    Quantise biases using the same per-class scale as weights.
    weight_scales[c] = Q15_MAX / max(abs(W[c]))
    """
    result = np.zeros(len(biases_float), dtype=np.int32)
    for c in range(len(biases_float)):
        result[c] = int(np.round(biases_float[c] * weight_scales[c]))
    return result


# ── C header writer ────────────────────────────────────────────────────────

def write_header(path, W_q15, b_q32, class_order, accuracy_cv):
    """
    Writes svm_q15_model.h.
    W_q15 : shape (NUM_CLASSES, NUM_FEATURES)  int16
    b_q32 : shape (NUM_CLASSES,)               int32
    """
    n_classes, n_feat = W_q15.shape

    lines = []
    lines.append("/*")
    lines.append(" * svm_q15_model.h")
    lines.append(" * Auto-generated by train_svm_rtl.py")
    lines.append(" *")
    lines.append(f" * Model    : LinearSVC, one-vs-rest")
    lines.append(f" * Features : {n_feat} (INT8 from RTL preprocessing)")
    lines.append(f" * Classes  : {n_classes}  ({' '.join(class_order)})")
    lines.append(f" * CV Acc   : {accuracy_cv:.1f}%  (leave-one-out on training set)")
    lines.append(" *")
    lines.append(" * Weight encoding: Q15 INT16  (scaled per class row)")
    lines.append(" * Bias encoding  : INT32      (same scale as weights)")
    lines.append(" *")
    lines.append(" * Inference (in c2000_classifier.c):")
    lines.append(" *   score[c] = bias[c] + sum(W[c][f] * x[f])  for f in 0..223")
    lines.append(" *   class_id = argmax(score) + 1   (1-indexed)")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef SVM_Q15_MODEL_H")
    lines.append("#define SVM_Q15_MODEL_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define SVM_NUM_CLASSES   {n_classes}")
    lines.append(f"#define SVM_NUM_FEATURES  {n_feat}")
    lines.append("")

    # Class name comments
    lines.append("/* Class index mapping (1-indexed on MCU): */")
    for i, name in enumerate(class_order):
        lines.append(f"/*   class_id {i+1} = {name} */")
    lines.append("")

    # Weights: [NUM_CLASSES][NUM_FEATURES]
    lines.append(f"const int16_t svm_weights[{n_classes}][{n_feat}] = {{")
    for c in range(n_classes):
        lines.append(f"    /* class {c+1}: {class_order[c]} */")
        lines.append("    {")
        row = W_q15[c]
        cols = 16
        for i in range(0, n_feat, cols):
            chunk = row[i:i+cols]
            row_str = ", ".join(f"{v:7d}" for v in chunk)
            comma = "," if (i + cols) < n_feat else ""
            lines.append(f"        {row_str}{comma}")
        closing = "    }," if c < n_classes - 1 else "    }"
        lines.append(closing)
    lines.append("};")
    lines.append("")

    # Biases: [NUM_CLASSES]
    bias_vals = ", ".join(f"{v:12d}" for v in b_q32)
    lines.append(f"const int32_t svm_biases[{n_classes}] = {{")
    lines.append(f"    {bias_vals}")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* SVM_Q15_MODEL_H */")

    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")


# ── Main ───────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Train SVM and generate svm_q15_model.h")
    parser.add_argument("--hex-dir", default="hex_files",      help="Folder with features_NNN.hex")
    parser.add_argument("--labels",  default="labels.txt",     help="Path to labels.txt")
    parser.add_argument("--output",  default="svm_q15_model.h",help="Output header file")
    args = parser.parse_args()

    # ── Load data ──────────────────────────────────────────────────────
    # Accept both features_NNN.hex and spectrum_NNN.hex naming conventions
    hex_files = sorted(glob.glob(os.path.join(args.hex_dir, "features_*.hex")))
    if not hex_files:
        hex_files = sorted(glob.glob(os.path.join(args.hex_dir, "spectrum_*.hex")))
    if not hex_files:
        sys.exit(f"ERROR: no features_*.hex or spectrum_*.hex files found in '{args.hex_dir}'")

    labels_dict = parse_labels(args.labels)

    X_list, y_list = [], []
    skipped = 0

    for hf in hex_files:
        basename = os.path.basename(hf)
        idx_str  = os.path.splitext(basename)[0].split("_")[-1]  # "007"

        if idx_str not in labels_dict:
            print(f"  [WARN] No label for '{idx_str}' — skipping {basename}")
            skipped += 1
            continue

        try:
            feat = parse_hex_file(hf)
        except ValueError as e:
            print(f"  [WARN] {e} — skipping")
            skipped += 1
            continue

        X_list.append(feat.astype(np.float32))
        y_list.append(labels_dict[idx_str])

    if not X_list:
        sys.exit("ERROR: no valid samples loaded")

    X = np.array(X_list, dtype=np.float32)   # (N, 224)
    y = np.array(y_list)                      # (N,)  string labels

    print(f"\nLoaded {len(X)} samples, {skipped} skipped")
    print(f"Classes in dataset: {sorted(set(y))}")

    # Enforce fixed class order matching MCU CLASS_NAMES[]
    for name in CLASS_NAMES:
        if name not in set(y):
            print(f"  [WARN] Class '{name}' has no samples — model may be unreliable")

    # ── Train LinearSVC ────────────────────────────────────────────────
    print("\nTraining LinearSVC...")
    clf = LinearSVC(
        C=0.1,              # regularisation — good default for small datasets
        max_iter=10000,
        dual=True,
        fit_intercept=True
    )
    clf.fit(X, y)

    # Cross-validation accuracy (leave-one-out style with cv=min(5, N))
    cv_folds = min(5, len(X))
    cv_scores = cross_val_score(clf, X, y, cv=cv_folds)
    cv_acc    = cv_scores.mean() * 100.0
    print(f"Cross-validation accuracy ({cv_folds}-fold): {cv_acc:.1f}%")

    # Training accuracy
    train_acc = clf.score(X, y) * 100.0
    print(f"Training accuracy: {train_acc:.1f}%")

    # ── Extract weights in CLASS_NAMES order ───────────────────────────
    # clf.classes_ may be in alphabetical order — reorder to match MCU
    clf_classes = list(clf.classes_)

    # Build weight matrix in fixed CLASS_NAMES order
    W_float = np.zeros((len(CLASS_NAMES), NUM_FEATURES), dtype=np.float64)
    b_float = np.zeros(len(CLASS_NAMES), dtype=np.float64)

    for target_idx, name in enumerate(CLASS_NAMES):
        if name not in clf_classes:
            print(f"  [WARN] '{name}' not in trained classes — weights set to 0")
            continue
        src_idx = clf_classes.index(name)
        if len(clf_classes) == 2:
            # Binary SVC: only one weight vector
            sign = 1 if src_idx == 1 else -1
            W_float[target_idx] = sign * clf.coef_[0]
            b_float[target_idx] = sign * clf.intercept_[0]
        else:
            W_float[target_idx] = clf.coef_[src_idx]
            b_float[target_idx] = clf.intercept_[src_idx]

    # ── Quantise to Q15 ────────────────────────────────────────────────
    print("\nQuantising weights to Q15...")

    # Compute per-class scale factors (saved for bias quantisation)
    weight_scales = np.zeros(len(CLASS_NAMES), dtype=np.float64)
    for c in range(len(CLASS_NAMES)):
        abs_max = np.max(np.abs(W_float[c]))
        weight_scales[c] = (Q15_MAX / abs_max) if abs_max > 0 else 1.0

    W_q15 = quantise_to_q15(W_float)
    b_q32 = quantise_bias_to_q15(b_float, weight_scales)

    # Verify quantisation error is small
    for c, name in enumerate(CLASS_NAMES):
        abs_max = np.max(np.abs(W_float[c]))
        if abs_max > 0:
            max_err = np.max(np.abs(W_float[c] - W_q15[c].astype(np.float64) / weight_scales[c]))
            rel_err = max_err / abs_max * 100.0
            print(f"  {name}: max weight quant error = {rel_err:.3f}%")

    # ── Write header ───────────────────────────────────────────────────
    write_header(args.output, W_q15, b_q32, CLASS_NAMES, cv_acc)

    print(f"\nWritten '{args.output}'")
    print(f"  Weight array : {len(CLASS_NAMES)} x {NUM_FEATURES} INT16"
          f"  = {len(CLASS_NAMES) * NUM_FEATURES * 2} bytes")
    print(f"  Bias array   : {len(CLASS_NAMES)} INT32"
          f"              = {len(CLASS_NAMES) * 4} bytes")
    print(f"  Total flash  : {len(CLASS_NAMES) * NUM_FEATURES * 2 + len(CLASS_NAMES) * 4} bytes")
    print("\nDrop svm_q15_model.h into your CCS project folder. Done.")


if __name__ == "__main__":
    main()